run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Checks for unused code

    # Additional recommended linters
    - gofmt         # Checks code is formatted
    - goimports     # Checks imports are formatted
    - misspell      # Finds commonly misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gocyclo       # Checks cyclomatic complexity
    - gocritic      # Provides many diagnostics
    - stylecheck    # Replacement for golint
    - exportloopref # Checks for pointers to enclosing loop variables
    - errorlint     # Find code that will cause problems with Go 1.13+ error wrapping
    - bodyclose     # Checks HTTP response body is closed
    - nilerr        # Finds code that returns nil even if error is checked
    - godot         # Checks comments end in a period
    - prealloc      # Finds slice declarations that could be preallocated

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jrh3k5/cryptonabber-offramp

  govet:
    enable-all: true
    disable:
      - shadow      # Can be too strict for some codebases

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false

  gosec:
    excludes:
      - G104  # Allow unhandled errors in some cases (covered by errcheck)

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Exclude specific issues by text
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - errcheck
        - gocritic

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
